- name: FileBeat Clear Other Version | 清除其他版本filebeat
  yum: name=filebeat state=absent

- name: FileBeat Group Add | 创建filebeat属组
  group:
    name: '{{pl_filebeat_user}}'
    gid:  '{{pl_filebeat_id}}'
    state: present
    
- name: FileBeat User Add | 创建filebeat用户
  user: 
    name:  '{{pl_filebeat_user}}'
    group: '{{pl_filebeat_user}}'
    uid:   '{{pl_filebeat_id}}'
    shell: /bin/bash
    state: present

- name: FileBeat Install Floder 创建filebeat目录
  file: 
    path:  '{{item}}' 
    state: 'directory'    
    mode: 0755
  with_items:
    - '{{pl_deploy_home}}'
    - '{{pl_filebeat_home}}'
    - '{{pl_filebeat_home}}/elastic'