- name: MongoDB Group | 创建mongodb属组
  group: 
    name: '{{pl_mongodb_user}}'
    gid:  '{{pl_mongodb_id}}'

- name: MongoDB User | 创建mongodb用户
  user: 
    name:  '{{pl_mongodb_user}}'
    group: '{{pl_mongodb_user}}'
    uid:   '{{pl_mongodb_id}}'
    shell: /bin/bash

- name: MongoDB Floder | 创建mongodb目录
  file: 
    path: '{{item}}'
    mode: 0755
    state: directory
  with_items:
    - '{{pl_mongodb_home}}/{{pl_role_type}}/{{pl_server_type}}'
    - '{{pl_mongodb_home}}/{{pl_role_type}}/{{pl_server_type}}/data'
    - '{{pl_mongodb_home}}/{{pl_role_type}}/{{pl_server_type}}/log'
    - '{{pl_mongodb_home}}/{{pl_role_type}}/{{pl_server_type}}/etc'
    - '{{pl_mongodb_home}}/{{pl_role_type}}/{{pl_server_type}}/pid'
    - '{{pl_mongodb_home}}/{{pl_role_type}}/{{pl_server_type}}/sock'

- name: MongoDB Source Packages | 解压mongodb软件包
  unarchive: 
    src:  'mongodb-linux-x86_64-rhel70-{{pl_mongodb_version}}.tgz' 
    dest: '{{pl_mongodb_home}}/{{pl_role_type}}/{{pl_server_type}}'

#- name: MongoDB Floder Name Change | 变更mongodb目录
#  command: mv mongodb-linux-x86_64-rhel70-{{pl_mongodb_version}} mongodb

- name: MongoDB Service | 将mongodb加入系统服务并生成配置文件
  template: 
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
  with_items:
    - { src: 'mongodb.service.j2', dest: '/usr/lib/systemd/system/mongodb.service' }
    - { src: 'mongodb.conf.j2',    dest: '{{pl_mongodb_home}}/{{pl_role_type}}/{{pl_server_type}}/etc/mongodb.conf' }
    
- name: MongoDB Floder Owner | 修改mongodb目录用户
  file: 
    path: '{{pl_mongodb_home}}/{{pl_role_type}}/{{pl_server_type}}' 
    owner: '{{pl_mongodb_user}}' 
    group: '{{pl_mongodb_user}}' 
    recurse: yes

- name: MongoDB Firewall | 开放mongodb防火墙限制
  firewalld: 
    port: '{{pl_mongodb_port}}/tcp'
    permanent: true 
    state: enabled

- name: MongoDB Start | 启动mongodb
  systemd: 
    name:  '{{item.name}}' 
    state: '{{item.state}}' 
    enabled: yes
  with_items:
    - { name: 'firewalld', state: 'reloaded' }
    - { name: 'mongodb',   state: 'started' }