- name: Deploy Floder | 创建安装包文件目录
  file: 
    path: '{{pl_deploy_home}}/support'  
    mode: 0755 
    state: directory

- name: Support Rpm Copy | 复制安装包文件到本地服务器
  copy: 
    src: support/
    dest: "{{pl_deploy_home}}/support"

- name: Support Rpm Install | 使用yum 安装库文件
  shell: /usr/bin/yum localinstall -y *
  args:
    chdir: '{{pl_deploy_home}}/support'
  #shell: /usr/bin/rpm -ivh --force {{pl_deploy_home}}/support/*.rpm

#- name: support_rpm_str
#  set_fact:
#    support_rpm_str: "{{ support_rpm_str | default('') }} {{ pl_deploy_home+'/support/'+item }}"
#  with_items:
#    - "{{ support_rpm }}"  
#- name: debug rpm_str    
#  debug: var=support_rpm_str

#- name: install support rpm by local yum
#  yum:
#    name: "{{support_rpm}}"
#    state: present
    #list: "{{pl_deploy_home}}/support/rpm_list.txt"
#    skip_broken: yes
 # register: result

#- name: debug
#  debug: var=result  