- name: Limits | 修改用户限制
  lineinfile: 
    dest: /etc/security/limits.conf
    insertbefore: '# End of file' 
    line: '{{item}}' 
    state: present 
    backup: yes    
  with_items:
    - '{{pl_config_user}}     hard   nproc   {{pl_hard_nproc}}'
    - '{{pl_config_user}}     soft   nproc   {{pl_soft_nproc}}'
    - '{{pl_config_user}}     hard   nofile  {{pl_hard_nofile}}'
    - '{{pl_config_user}}     soft   nofile  {{pl_soft_nofile}}'
    - '{{pl_config_user}}     hard   memlock {{pl_hard_memlock}}'
    - '{{pl_config_user}}     soft   memlock {{pl_soft_memlock}}'
 
#- name: Ulimit |
#  lineinfile:
#    dest: /etc/rc.local
#    regexp: 'ulimit -s unlimited'
#    backrefs: no
#    line: 'ulimit -s unlimited'

- name: Sysctl | 优化内核参数
  sysctl:
    name:  '{{item.name}}'
    value: '{{item.value}}'
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - '{{sysctl_items}}'

- name: Kernel_THP | 关闭透明大页
  shell: '{{item}}'
  with_items:
    - 'echo "{{pl_transparent_hugepage}}" > /sys/kernel/mm/transparent_hugepage/enabled'
    #- 'setenforce 0'
    #- 'hostname {{pl_hostname}}'
    #- 'ulimit -s unlimited'