- name: Plat Nginx Service | 将nginx加入系统服务
  template: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - { src: 'nginx.service.j2'  ,dest: '/usr/lib/systemd/system/nginx.service' }

- name: Plat Nginx Firewall | 为nginx开启防火墙限制
  firewalld: port='{{item}}' permanent=true state=enabled
  with_items:
    - '80/tcp'
    - '8088/tcp'
    - '443/tcp'
    - '80/tcp'
    - '8015/tcp'
  
- name: Plat Nginx Floder Owner | 变更nginx目录用户
  file: path='{{pl_nginx_home}}/{{pl_role_type}}/{{pl_server_type}}' owner='{{pl_nginx_user}}' group='{{pl_nginx_user}}' recurse=yes  
    
- name: Plat Nginx Start | 启动nginx
  systemd: name='{{item.name}}' state='{{item.state}}' enabled=yes
  with_items:
    - { name: 'firewalld',state: 'reloaded' }
    - { name: 'nginx',    state: 'restarted' }