#check dscore
- name: check dscore
  stat: 
    path: '{{home}}/dscore'
  #ignore_errors: yes
  register: dscore_status
#check nginx
- name: check nginx
  stat: 
    path: '{{home}}/nginx'
  #ignore_errors: yes
  register: nginx_status

#config dscore 
- name: filebeat-dscore
  template:
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
  with_items:
    - { src: 'ds_filebeat.yml.j2', dest: '{{pl_mon_home}}/filebeat-{{pl_filebeat_version}}-linux-x86_64/filebeat.yml' }
  when: dscore_status.stat.exists and nginx_status.stat.exists == False
#config nginx  
- name: filebeat-nginx
  template:
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
  with_items:
    - { src: 'ng_filebeat.yml.j2', dest: '{{pl_mon_home}}/filebeat-{{pl_filebeat_version}}-linux-x86_64/filebeat.yml' }
  when: nginx_status.stat.exists and dscore_status.stat.exists == False
#config all
- name: filebaet-all
  template:
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
  with_items:
    - { src: 'filebeat.yml.j2', dest: '{{pl_mon_home}}/filebeat-{{pl_filebeat_version}}-linux-x86_64/filebeat.yml' }
  when: dscore_status.stat.exists and nginx_status.stat.exists 
