- name: filebeat-service config
  template:
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
  with_items:
    - { src: 'filebeat.service.j2',dest: '/lib/systemd/system/filebeat.service' }
    
- name: start filebeat
  systemd: name='{{item.name}}' state='{{item.state}}' enabled=yes
  with_items:
    - { name: 'filebeat',    state: 'restarted' }