- name: add group for zabbix
  group: 
    name: '{{pl_zbx_group}}' 
    gid:  '{{pl_zbx_gid}}'

- name: add user for zabbix
  user: 
    name:  '{{pl_zbx_user}}'
    group: '{{pl_zbx_group}}'    
    uid:   '{{pl_zbx_uid}}' 
    shell: /bin/bash

- name: make floder for use 
  file: 
    path:  '{{item.path}}' 
    owner: '{{item.owner}}' 
    group: '{{item.group}}' 
    mode: 0755 
    state: directory
  with_items:
    - { path: '{{pl_deploy_home}}',        owner: 'root',group: 'root' }
    - { path: '{{pl_mon_home}}',           owner: 'root',group: 'root' }
    - { path: '{{pl_mon_home}}/zabbix',    owner: '{{pl_zbx_user}}',group: '{{pl_zbx_group}}' }    
    - { path: '{{pl_mon_home}}/zabbix/run',owner: '{{pl_zbx_user}}',group: '{{pl_zbx_group}}' }
    - { path: '{{pl_mon_home}}/zabbix/etc',owner: '{{pl_zbx_user}}',group: '{{pl_zbx_group}}' }        
    - { path: '{{pl_mon_home}}/zabbix/log',owner: '{{pl_zbx_user}}',group: '{{pl_zbx_group}}' }  


- name: extract zabbix agent source packages
  unarchive: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - { src: 'zabbix-{{pl_zabbix_version}}.tar.gz',                 dest: '{{pl_deploy_home}}' }
    - { src: 'filebeat-{{pl_filebeat_version}}-linux-x86_64.tar.gz',dest: '{{pl_mon_home}}' }
    - { src: 'jdk-{{pl_jdk_version}}-linux-x64.tar.gz',             dest: '{{pl_mon_home}}/zabbix/etc' }

- name: make zabbix agent
  command: ./configure --prefix={{pl_mon_home}}/zabbix --sysconfdir={{pl_mon_home}}/zabbix/etc --with-ldap --with-openssl --enable-ipv6 --enable-agent
  args:
    chdir: '{{pl_deploy_home}}/zabbix-{{pl_zabbix_version}}'

- name: install zabbix agent
  make:
    chdir: '{{pl_deploy_home}}/zabbix-{{pl_zabbix_version}}'
    target: install
    params:
      NUM_THREADS: 4
  
- name: zabbix scripts
  copy: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - { src: 'scripts', dest: '{{pl_mon_home}}/zabbix/etc' }