- name: make floder for use 
  file: 
    path:  '{{item.path}}' 
    mode: 0755 
    state: directory
  with_items:
    - { path: '{{pl_bak_home}}' }
    - { path: '{{pl_bak_home}}/scripts' }

- name: bakup scripts
  template:
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
    mode: 0755
  with_items:
    - { src: 'bakup/mysql_db_backup.sh.j2',     dest: '{{pl_bak_home}}/scripts/mysql_db_backup.sh' }
    - { src: 'bakup/nginx_log_backup.sh.j2',    dest: '{{pl_bak_home}}/scripts/nginx_log_backup.sh' }
    - { src: 'bakup/redis_db_backup.sh.j2',     dest: '{{pl_bak_home}}/scripts/redis_db_backup.sh' }
    - { src: 'bakup/tomcat_log_backup.sh.j2',   dest: '{{pl_bak_home}}/scripts/tomcat_log_backup.sh' }
    - { src: 'bakup/web4node_node_bakup.sh.j2', dest: '{{pl_bak_home}}/scripts/web4node_node_bakup.sh' }
    
- name: bakup scripts crontab
  cron:
    name:   '{{item.name}}'
    minute: '{{item.minute}}'
    hour:   '{{item.hour}}'
    job:    '{{item.job}}'
  with_items:
    - { name: 'Backup MysqlDB',   minute: '0',  hour: '1',job: 'bin/bash {{pl_bak_home}}/scripts/mysql_db_backup.sh &>/dev/null'  }
    - { name: 'Backup NginxLog',  minute: '30', hour: '1',job: 'bin/bash {{pl_bak_home}}/scripts/nginx_log_backup.sh &>/dev/null'  }
    - { name: 'Backup TomcatLog', minute: '30', hour: '1',job: 'bin/bash {{pl_bak_home}}/scripts/tomcat_log_backup.sh &>/dev/null'  }
    - { name: 'Backup RedisDB',   minute: '0',  hour: '2',job: 'bin/bash {{pl_bak_home}}/scripts/redis_db_backup.sh &>/dev/null'  }
    - { name: 'Backup Web4node',  minute: '0',  hour: '2',job: 'bin/bash {{pl_bak_home}}/scripts/web4node_node_bakup.sh &>/dev/null'  }
    
- name: copy paas
  copy:
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
    mode: 0755
  with_items:
    - { src: 'paas', dest: '/etc/init.d/paas' }