- hosts: mysql
  vars: 
    user: plat
    group: plat
    uid: 8080
    gid: 8080
    home: /home/plat
    samba_mount_path: '{{home}}/share_path'
    samba_workgroup: plat
  roles:
     - install_support
     - system_config
     - samba_source
