#基础配置
#- hosts: test_dscore_cluster_company:test_plat_cluster_company
#  roles:
#    - { role: system_config, yum_repo: tsinghua }
#入口
- hosts: test_plat_cluster_company
  vars: 
    role_type: plat
  roles:    
    - plat_nginx_source
    - { role: plat_mysql_source, mysql_port: 33333, mysql_db_user: mysqltest, mysql_db_pwd: mysqltest@WSX }
    - { role: plat_redis_source, redis_pwd: redistest@WSX }
    - plat_node
    - { role: samba_source, samba_port: 44444, samba_password: sambatest@WSX }
    - { role: squid_source, squid_port: 55555 }
#挂载
- hosts: test_dscore_cluster_company:!test_plat_cluster_company  
  roles:      
    - { role: samba_mount, samba_port: 44444, samba_password: sambatest@WSX }
#集群
- hosts: test_dscore_cluster_company
#- hosts: test_dscore_cluster_company:!test_plat_cluster_company
  vars: 
    role_type: plat
  roles:
    - zookeeper
    - kafka
    - { role: tomcat, role_type: plat, server_type: dscore, tomcat_user: plat, tomcat_path: /ds, ds_mysql_port: 33066, ds_mysql_db_user: mysqltest, ds_mysql_db_pwd: mysqltest@WSX, ds_squid_port: 55555, ds_redis_pwd: redistest@WSX }
#agent
- hosts: test_dscore_cluster_company:test_plat_cluster_company
  roles:    
    - { role: zabbix_agent, zabbix_redis_password: redistest@WSX, zabbix_server: 192.168.228.201 }
    - { role: filebeat, logstash_server: 192.168.228.201 }
    - plat_paas 
    - plat_backup
#empi
- hosts: test_plat_cluster_company
  roles:
    - { role: mongodb, role_type: empi, mongodb_ip: '127.0.0.1,172.16.140.237' }  
    - { role: solr, role_type: empi, solr_core: empi }
    - { role: tomcat, role_type: empi, server_type: empi, tomcat_user: empi, tomcat_id: 9090, tomcat_port: 8096, tomcat_shutdown_port: 8006, tomcat_redirectPort: 8446, tomcat_protocol_port: 8010, tomcat_jmx_port: 10001, tomcat_path: /empi, empi_squid_port: 55555 }
