- name: Plat Redis Bin | 复制编译完成redis执行文件
  copy: src='{{item.src}}' dest='{{item.dest}}' remote_src=yes mode=755
  with_items:
    - { src: '{{pl_deploy_home}}/redis-{{pl_redis_version}}/src/redis-benchmark',dest: '{{pl_redis_home}}/{{pl_role_type}}/{{pl_server_type}}/bin/redis-benchmark' }
    - { src: '{{pl_deploy_home}}/redis-{{pl_redis_version}}/src/redis-check-aof',dest: '{{pl_redis_home}}/{{pl_role_type}}/{{pl_server_type}}/bin/redis-check-aof' }
    - { src: '{{pl_deploy_home}}/redis-{{pl_redis_version}}/src/redis-check-rdb',dest: '{{pl_redis_home}}/{{pl_role_type}}/{{pl_server_type}}/bin/redis-check-rdb' }
    - { src: '{{pl_deploy_home}}/redis-{{pl_redis_version}}/src/redis-cli',      dest: '{{pl_redis_home}}/{{pl_role_type}}/{{pl_server_type}}/bin/redis-cli' }
    - { src: '{{pl_deploy_home}}/redis-{{pl_redis_version}}/src/redis-sentinel', dest: '{{pl_redis_home}}/{{pl_role_type}}/{{pl_server_type}}/bin/redis-sentinel' }
    - { src: '{{pl_deploy_home}}/redis-{{pl_redis_version}}/src/redis-server',   dest: '{{pl_redis_home}}/{{pl_role_type}}/{{pl_server_type}}/bin/redis-server' }

- name: Plat Redis Cli | 为redis执行文件建立软连接
  file: src='{{pl_redis_home}}/{{pl_role_type}}/{{pl_server_type}}/bin/redis-cli' dest='/usr/bin/redis-cli' state=link
  
- name: Plat Redis Config | 生成redis配置文件
  template: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - { src: 'redis.conf.j2',          dest: '{{pl_redis_home}}/{{pl_role_type}}/{{pl_server_type}}/etc/redis.conf' }
    - { src: 'redis-server.service.j2',dest: '/lib/systemd/system/redis-server.service' }  