- name: Plat Redis Group | 创建redis属组
  group: 
    name: '{{pl_redis_user}}' 
    gid:  '{{pl_redis_id}}'

- name: Plat Redis User | 创建redis用户
  user: 
    name:  '{{pl_redis_user}}'
    group: '{{pl_redis_user}}'    
    uid:   '{{pl_redis_id}}' 
    shell: /bin/bash

- name: Plat Redis Floder | 创建redis目录
  file: 
    path: '{{item}}' 
    mode: 0755 
    state: directory
  with_items:
    - '{{pl_deploy_home}}'
    - '{{pl_redis_home}}'
    - '{{pl_redis_home}}/{{pl_role_type}}'
    - '{{pl_redis_home}}/{{pl_role_type}}/{{pl_server_type}}'
    - '{{pl_redis_home}}/{{pl_role_type}}/{{pl_server_type}}/data'
    - '{{pl_redis_home}}/{{pl_role_type}}/{{pl_server_type}}/etc'
    - '{{pl_redis_home}}/{{pl_role_type}}/{{pl_server_type}}/bin'
    - '{{pl_redis_home}}/{{pl_role_type}}/{{pl_server_type}}/pid'
    - '{{pl_redis_home}}/{{pl_role_type}}/{{pl_server_type}}/log'