- name: Tomcat Floder Owner | 变更tomcat目录所有者
  file: 
    path:  '{{item}}' 
    owner: '{{pl_tomcat_user}}' 
    group: '{{pl_tomcat_user}}' 
    recurse: yes
  with_items:
    - '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}'

- name: Tomcat start | 启动tomcat
  systemd: 
    name:  '{{pl_server_type}}' 
    state: started
    enabled: yes

- name: Dscore Keygen Info Wait | 等待ds项目生成info文件
  wait_for:
    path: '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}/ds/WEB-INF/info'
    #path: '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}/apache-tomcat-{{pl_tomcat_version}}/webapps/ds/WEB-INF/info'
    delay: 10
    timeout: 6000

- name: Dscore Keygen Package | 解压注册机
  unarchive: 
    src:     '{{item.src}}' 
    dest:    '{{item.dest}}'
  with_items:
    - { src: 'ds/Generator.tar.gz',dest: '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}' }
    
- name: Dscore Keygen Info File | 复制info文件到指定目录
  copy: 
    src:  '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}/ds/WEB-INF/info'
    #src:  '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}/apache-tomcat-{{pl_tomcat_version}}/webapps/ds/WEB-INF/info'
    dest: '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}/Generator/bin/info'
    remote_src: yes

- name: Dscore Keygen Key | 生成授权文件
  command: '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}/jdk{{pl_jdk_version}}/bin/java -Djava.ext.dirs={{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}/Generator generator.Generator'
  args:
    chdir: '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}/Generator/'

- name: Dscore Keygen Key File | 复制授权文件到项目目录
  copy: 
    src:  '{{item.src}}' 
    dest: '{{item.dest}}' 
    remote_src: yes
  with_items:
    - { src: '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}/Generator/bin/pc', dest: '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}/ds/WEB-INF/classes/pc' }
    #- { src: '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}/Generator/bin/pc', dest: '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}/apache-tomcat-{{pl_tomcat_version}}/webapps/ds/WEB-INF/classes/pc' }
    - { src: '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}/Generator/bin/key',dest: '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}/ds/WEB-INF/classes/key' }
    #- { src: '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}/Generator/bin/key',dest: '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}/apache-tomcat-{{pl_tomcat_version}}/webapps/ds/WEB-INF/classes/key' }

- name: Dscore Keygen Clear | 清理注册机
  file: 
    path:  '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}/Generator/'
    state: absent