- name: add group for kafka
  group: 
    name: '{{group}}' 
    gid: '{{gid}}'

- name: add user for kafka
  user: 
    name: '{{user}}'
    group: '{{group}}'    
    uid: '{{uid}}' 
    home: '{{home}}' 
    shell: /bin/bash

- name: make floder for use 
  file: 
    path: '{{item.path}}' 
    owner: '{{item.owner}}' 
    group: '{{item.group}}' 
    mode: 0755 
    state: '{{item.state}}'
  with_items:
    - { path: '{{deploy_home}}',owner: 'root',group: 'root',state: 'directory' }
    - { path: '{{home}}/kafka',owner: '{{user}}',group: '{{group}}',state: 'directory' }
    - { path: '{{home}}/kafka/logs',owner: '{{user}}',group: '{{group}}',state: 'directory' }
    - { path: '{{home}}/zookeeper',owner: '{{user}}',group: '{{group}}',state: 'directory' }
    - { path: '{{home}}/zookeeper/zkdata',owner: '{{user}}',group: '{{group}}',state: 'directory' }
    - { path: '{{home}}/zookeeper/zkdatalog',owner: '{{user}}',group: '{{group}}',state: 'directory' }
    - { path: '{{home}}/zookeeper/logs',owner: '{{user}}',group: '{{group}}',state: 'directory' }
    - { path: '{{home}}/zookeeper/zkdata/myid',owner: '{{user}}',group: '{{group}}',state: 'touch' } 

- name: zookeeper server id
  command: echo "1" > {{home}}/zookeeper/zkdata/myid  
    
- name: extract zookeeper & kafka source packages
  unarchive: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - { src: 'kafka_{{kafka_version}}.tgz',dest: '{{home}}/kafka' }
    - { src: 'zookeeper-{{zookeeper_version}}.tar.gz',dest: '{{home}}/zookeeper' }
    - { src: 'jdk-{{jdk_version}}-linux-x64.tar.gz',dest: '{{home}}' }

- name: change floder owner
  file: path='{{home}}/jdk{{jdk_version}}' owner='{{user}}' group='{{group}}' recurse=yes 
  
- name: config zookeeper & kafka
  template: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - { src: 'server.properties.j2',dest: '{{home}}/kafka/kafka_{{kafka_version}}/config/server.properties' }
    - { src: 'kafka.service.j2',dest: '/lib/systemd/system/kafka.service' }
    - { src: 'zoo.cfg.j2',dest: '{{home}}/zookeeper/zookeeper-{{zookeeper_version}}/conf/zoo.cfg' }
    - { src: 'log4j.properties.j2',dest: '{{home}}/zookeeper/zookeeper-{{zookeeper_version}}/conf/log4j.properties' }
    - { src: 'zookeeper.service.j2',dest: '/lib/systemd/system/zookeeper.service' } 

- name: firewall zookeeper & kafka
  firewalld: port={{item}}/tcp permanent=true state=enabled
  with_items:
    - '{{kafka_port}}'
    - '{{kafka_jmx_port}}'
    - '{{zookeeper_port}}'
    - '{{zookeeper_jmx_port}}'
  
- name: change floder zookeeper & kafka
  file: path='{{item}}' owner='{{user}}' group='{{group}}' recurse=yes
  with_items:
    - '{{home}}/kafka'
    - '{{home}}/zookeeper'

- name: start zookeeper & kafka
  systemd: name='{{item.name}}' state='{{item.state}}' enabled=yes
  with_items:
    - { name: 'firewalld',state: 'reloaded' }
    - { name: 'kafka',state: 'started' }
    - { name: 'zookeeper',state: 'started' }