home: /home/plat
deploy_home: /home/deploy
user: plat
group: "{{user}}"
uid: 8080
gid: "{{uid}}"
tomcat_version: 8.5.37
jdk_version: 1.8.0_191
tomcat_shutdown_port: 8005
tomcat_port: 8080
connectionTimeout: 20000
tomcat_redirectPort: 8447
tomcat_protocol_port: 8025
tomcat_host: localhost
tomcat_appName: localhost
tomcat_appBase: webapps
tomcat_jmx_port: 10000
tomcat_native_version: 1.2.19