- name: add group for tomcat
  group: 
    name: '{{group}}' 
    gid: '{{gid}}'

- name: add user for tomcat
  user: 
    name: '{{user}}'
    group: '{{group}}'    
    uid: '{{uid}}' 
    home: '{{home}}' 
    shell: /bin/bash

- name: make floder for use 
  file: 
    path: '{{item.path}}' 
    owner: '{{item.owner}}' 
    group: '{{item.group}}' 
    mode: 0755 
    state: directory
  with_items:
    - { path: '{{deploy_home}}',owner: 'root',group: 'root' }
    - { path: '{{home}}',owner: '{{user}}',group: '{{group}}' }
    - { path: '{{home}}/ds-log',owner: '{{user}}',group: '{{group}}' }

- name: extract tomcat source packages
  unarchive: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - { src: 'apache-tomcat-{{tomcat_version}}.tar.gz',dest: '{{home}}' }
    - { src: 'jdk-{{jdk_version}}-linux-x64.tar.gz',dest: '{{home}}' }

- name: change floder owner
  file: path='{{home}}/jdk{{jdk_version}}' owner='{{user}}' group='{{group}}' recurse=yes  
    
- name: rename floder tomcat
  command: mv {{home}}/apache-tomcat-{{tomcat_version}} {{home}}/dscore
  
- name: check tomcat-native
  shell: ls /usr/local/apr/lib/libtcnative-1.so
  ignore_errors: yes
  register: tomcat_native_status

- import_tasks: make_tomcat_native.yml
  when: tomcat_native_status is failed 

- name: mk floger tomcat
  file:
    path: '{{item.path}}'
    state: '{{item.state}}'
  with_items:
    - { path: '{{home}}/dscore/webapps', state: 'absent' }
    - { path: '{{home}}/dscore/webapps', state: 'directory' }
  
- name: config tomcat
  template: 
    src: '{{item.src}}' 
    dest: '{{item.dest}}' 
  with_items:
    - { src: 'server.xml.j2',dest: '{{home}}/dscore/conf/server.xml' }
    - { src: 'setenv.sh.j2',dest: '{{home}}/dscore/bin/setenv.sh' }
    - { src: 'dscore.service.j2',dest: '/lib/systemd/system/dscore.service' }
    
- name: fire wall tomcat
  firewalld: port={{tomcat_port}}/tcp permanent=true state=enabled
  
- name: change floder owner
  file: path='{{home}}/dscore' owner='{{user}}' group='{{group}}' recurse=yes  
    
- name: start tomcat
  systemd: name='{{item.name}}' state='{{item.state}}' enabled=yes
  with_items:
    - { name: 'firewalld',state: 'reloaded' }
    - { name: 'dscore',state: 'started' }