- import_tasks: plat_dscore_prepare.yml
  tags:
    - plat_dscore_prepare

- import_tasks: plat_dscore_tomcat.yml
  tags:
    - plat_dscore_tomcat

- import_tasks: plat_dscore.yml
  tags:
    - plat_dscore
  
- import_tasks: plat_dscore_start.yml
  tags:
    - plat_dscore_start