- name: Plat Dscore Tomcat Group
  group: 
    name: '{{pl_dscore_group}}' 
    gid:  '{{pl_dscore_gid}}'

- name: Plat Dscore Tomcat User
  user: 
    name:  '{{pl_dscore_user}}'
    group: '{{pl_dscore_group}}'    
    uid:   '{{pl_dscore_uid}}' 
    shell: /bin/bash

- name: Plat Dscore Tomcat Floder 
  file: 
    path:  '{{item.path}}' 
    owner: '{{item.owner}}' 
    group: '{{item.group}}' 
    mode: 0755 
    state: directory
  with_items:
    - { path: '{{pl_dscore_home}}/ds-log',owner: '{{pl_dscore_user}}',group: '{{pl_dscore_group}}' }