- import_tasks: nginx_user.yml
  tags: Nginx User(with floder)

- import_tasks: nginx_package.yml
  tags: Nginx Package 
  
- import_tasks: nginx_make.yml
  tags: Nginx Make
 
- import_tasks: nginx_conf.yml
  tags: Nginx Config
    
- import_tasks: nginx_service.yml
  tags: Nginx Service(with firewall)
