#nginx编译安装前准备
- import_tasks: nginx_prepare.yml
  tags:
    - nginx_prepare
#nginx编译安装
- import_tasks: nginx_make.yml
  tags:
    - nginx_make
#nginx生成配置文件
- import_tasks: nginx_conf.yml
  tags:
    - nginx_conf
#nginx安装任务完成
- import_tasks: nginx_start.yml
  tags:
    - nginx_start