- name:  service nginx
  template: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - { src: 'nginx.service.j2'  ,dest: '/usr/lib/systemd/system/nginx.service' }

- name: firewall nginx
  firewalld: port=80/tcp permanent=true state=enabled
  
- name: change floder owner
  file: path='{{pl_home}}/nginx' owner='{{pl_user}}' group='{{pl_group}}' recurse=yes  
    
- name: start nginx
  systemd: name='{{item.name}}' state='{{item.state}}' enabled=yes
  with_items:
    - { name: 'firewalld',state: 'reloaded' }
    - { name: 'nginx',    state: 'restarted' }