- name: check jemalloc
  shell: ls /usr/local/lib/libjemalloc.so.2
  ignore_errors: yes
  register: jemalloc_status

- import_tasks: make_jemalloc.yml
  when: jemalloc_status is failed 
 
- name: check luajit
  shell: ls /usr/local/lib/libluajit-5.1.so.2
  ignore_errors: yes
  register: luajit_status
  
- import_tasks: make_luajit.yml
  when: luajit_status is failed 
    
- name: extract nginx source packages
  unarchive: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - { src: 'nginx-{{pl_nginx_version}}.tar.gz',                      dest: '{{pl_deploy_home}}' }
    - { src: 'pcre-{{pl_pcre_version}}.tar.gz',                        dest: '{{pl_deploy_home}}' }
    - { src: 'zlib-{{pl_zlib_version}}.tar.gz',                        dest: '{{pl_deploy_home}}' }
    - { src: 'openssl-{{pl_openssl_version}}.tar.gz',                  dest: '{{pl_deploy_home}}' }
    - { src: 'ngx_devel_kit-{{pl_ngx_devel_kit_version}}.tar.gz',      dest: '{{pl_deploy_home}}' }   
    - { src: 'lua-nginx-module-{{pl_lua_nginx_module_version}}.tar.gz',dest: '{{pl_deploy_home}}' }
    - { src: 'naxsi-{{pl_naxsi_version}}.tar.gz',                      dest: '{{pl_deploy_home}}' }
 