#nginx完成
#nginx防火墙
- name: 为Nginx开启防火墙限制
  firewalld: 
    port: "{{item}}"
    permanent: true 
    state: enabled
  with_items:
    - '80/tcp'
    - '8088/tcp'
    - '443/tcp'
    - '80/tcp'
    - '8015/tcp'
#nginx服务器启动
- name: 启动Nginx
  systemd: 
    name: "{{item.name}}"
    state: "{{item.state}}"
    enabled: yes
  with_items:
    - { name: 'firewalld',state: 'reloaded' }
    - { name: 'nginx', state: 'restarted' }
#nginx源码包清理
- name: Delete Setup Files | 清理安装过程中的文件
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - '/home/deploy/nginx-{{pl_nginx_version}}'
    - '/home/deploy/nginx-{{pl_nginx_version}}.tar.gz'
    - '/home/deploy/pcre-{{pl_pcre_version}}'
    - '/home/deploy/pcre-{{pl_pcre_version}}.tar.gz'
    - '/home/deploy/zlib-{{pl_zlib_version}}'
    - '/home/deploy/zlib-{{pl_zlib_version}}.tar.gz'
    - '/home/deploy/openssl-{{pl_openssl_version}}'
    - '/home/deploy/openssl-{{pl_openssl_version}}.tar.gz'
    - '/home/deploy/ngx_devel_kit-{{pl_ngx_devel_kit_version}}'
    - '/home/deploy/ngx_devel_kit-{{pl_ngx_devel_kit_version}}.tar.gz'
    - '/home/deploy/lua-nginx-module-{{pl_lua_nginx_module_version}}'
    - '/home/deploy/lua-nginx-module-{{pl_lua_nginx_module_version}}.tar.gz'
    - '/home/deploy/naxsi-{{pl_naxsi_version}}'
    - '/home/deploy/naxsi-{{pl_naxsi_version}}.tar.gz'
    - '/home/deploy/jemalloc-{{pl_jemalloc_version}}'
    - '/home/deploy/jemalloc-{{pl_jemalloc_version}}.tar.gz'
    - '/home/deploy/luajit2-{{pl_luajit2_version}}'
    - '/home/deploy/luajit2-{{pl_luajit2_version}}.tar.gz'
    - '/home/deploy/nginx-dav-ext-module-{{pl_nginx_dav_ext_module_version}}'
    - '/home/deploy/nginx-dav-ext-module-{{pl_nginx_dav_ext_module_version}}.tar.gz'