#nginx运行用户
- name: 创建Nginx属组
  group: 
    name: nginx 
    gid: 8000
- name: 创建Nginx用户
  user: 
    name: nginx
    group: nginx  
    uid: 8000
    create_home: no
    shell: /sbin/nologin
#nginx运行目录
- name: 创建Nginx目录
  file: 
    path: "{{item.path}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: 0755 
    state: "{{item.state}}"
  with_items:
    - { path: '/home/deploy', owner: root, group: root, state: directory }
    - { path: '/home/plat', owner: root, group: root, state: directory }
    - { path: '/home/plat/nginx', owner: nginx, group: nginx, state: directory }
    - { path: '/home/plat/nginx/conf', owner: nginx, group: nginx, state: directory }
    - { path: '/home/plat/nginx/conf/conf.d', owner: nginx, group: nginx, state: directory }
    - { path: '/home/plat/nginx/conf/ssl', owner: nginx, group: nginx, state: directory }
#nginx运行库
- import_tasks: rpm/online.yml
  when: pl_setup_type == "online"
- import_tasks: rpm/offline.yml
  when: pl_setup_type == "offline"
#nginx源码包下载
- import_tasks: package/online.yml
  when: pl_setup_type == "online"
- import_tasks: package/offline.yml
  when: pl_setup_type == "offline"
#nginx源码包解压缩
- name: 解压Nginx软件包
  unarchive: 
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    remote_src: yes
  with_items:
    - { src: '/home/deploy/nginx-{{pl_nginx_version}}.tar.gz', dest: /home/deploy }
    - { src: '/home/deploy/pcre-{{pl_pcre_version}}.tar.gz', dest: /home/deploy }
    - { src: '/home/deploy/zlib-{{pl_zlib_version}}.tar.gz', dest: /home/deploy }
    - { src: '/home/deploy/openssl-{{pl_openssl_version}}.tar.gz', dest: /home/deploy }
    - { src: '/home/deploy/ngx_devel_kit-{{pl_ngx_devel_kit_version}}.tar.gz', dest: /home/deploy }
    - { src: '/home/deploy/lua-nginx-module-{{pl_lua_nginx_module_version}}.tar.gz',dest: /home/deploy }
    - { src: '/home/deploy/naxsi-{{pl_naxsi_version}}.tar.gz', dest: /home/deploy }
    - { src: '/home/deploy/jemalloc-{{pl_jemalloc_version}}.tar.gz', dest: /home/deploy }
    - { src: '/home/deploy/luajit2-{{pl_luajit2_version}}.tar.gz', dest: /home/deploy }
    - { src: '/home/deploy/nginx-dav-ext-module-{{pl_nginx_dav_ext_module_version}}.tar.gz', dest: /home/deploy }
#jemalloc安装
- name: 检查Jemalloc
  stat: path='/usr/local/lib/libjemalloc.so.2'
  register: jemalloc
- import_tasks: plugin/jemalloc.yml
  when: jemalloc.stat.exists == False
#luajit2安装
- name: 检查Luajit2
  stat: path='usr/local/lib/libluajit-*.so.2'
  register: luajit
- import_tasks: plugin/luajit.yml
  when: luajit.stat.exists == False