- import_tasks: plat_prepare.yml
  tags:
    - plat_prepare

- import_tasks: plat_support.yml
  tags:
    - plat_support

- import_tasks: plat_system_config.yml
  tags: 
    - plat_system_config
 
- name: Plat YumRepo NtpConf
  copy:
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
  with_items:
    - { src: 'centos7_{{pl_yum_repo}}_CentOS-Base.repo',dest: '/etc/yum.repos.d/CentOS-Base.repo' }
    - { src: '{{pl_ntpserver}}_ntp.conf',               dest: '/etc/ntp.conf' }    
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags:
    - plat_yumrepo_ntpconf  

- name: Plat Selinux
  selinux:
    state: disabled
  tags:
    - plat_selinux

- name: Plat Timezone 
  timezone:
    name: '{{pl_timezone}}'
  tags:
    - plat_timezone

- name: Plat Hostname
  hostname:
    name: '{{pl_hostname}}'
  tags:
    - plat_hostname

- name: Plat Hosts
  lineinfile:
    line: '{{hosts_list}}'
    path: '/etc/hosts'
    backup: yes
  tags:
    - plat_hosts
  
- name: Plat Server Reboot
  reboot:
    reboot_timeout: 300
  tags:
    - plat_server_reboot