- name: Config Selinux
  selinux:
    state: disabled
  tags: Config Selinux
  
- name: Config Limits 
  lineinfile: 
    dest: /etc/security/limits.conf
    insertbefore: '# End of file' 
    line: '{{item}}' 
    state: present 
    backup: yes    
  with_items:
    - '{{pl_config_user}}     hard   nproc   {{pl_hard_nproc}}'
    - '{{pl_config_user}}     soft   nproc   {{pl_soft_nproc}}'
    - '{{pl_config_user}}     hard   nofile  {{pl_hard_nofile}}'
    - '{{pl_config_user}}     soft   nofile  {{pl_soft_nofile}}'
    - '{{pl_config_user}}     hard   memlock {{pl_hard_memlock}}'
    - '{{pl_config_user}}     soft   memlock {{pl_soft_memlock}}'
  tags: Config Limits 
 
- name: Config YumRepo & NtpConf
  copy:
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
  with_items:
    - { src: 'centos7_{{pl_yum_repo}}_CentOS-Base.repo',dest: '/etc/yum.repos.d/CentOS-Base.repo' }
    - { src: '{{pl_ntpserver}}_ntp.conf',               dest: '/etc/ntp.conf' }    
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags: Config YumRepo & NtpConf 

- name: Config Timezone 
  timezone:
    name: '{{pl_timezone}}'
  tags: Config Timezone 

- name: Config Sysctl
  sysctl:
    name:  '{{item.name}}'
    value: '{{item.value}}'
    sysctl_set: yes
    state: '{{item.state}}'
    reload: yes
  with_items:
    - { name: 'vm.swappiness',       value: '{{pl_vm_swappiness}}',          state: present }
    - { name: 'vm.max_map_count',    value: '{{pl_vm_max_map_count}}',       state: present }
    - { name: 'vm.overcommit_memory',value: '{{pl_vm_overcommit_memory}}',   state: present }
    - { name: 'net.core.somaxconn',  value: '{{pl_net_core_somaxconn}}',     state: present }
  tags: Config Sysctl

- name: Config Kernel transparent_hugepage & enforece & hostname 
  shell: '{{item}}'
  with_items:
    - 'echo "{{pl_transparent_hugepage}}" > /sys/kernel/mm/transparent_hugepage/enabled'
    - 'setenforce 0'
    - 'hostname {{pl_hostname}}'
  tags: Config Kernel

- name: Config Hostname
  hostname:
    name: '{{pl_hostname}}'
  tags: Config Hostname

- name: Config Hosts
  template:
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
  with_items:
    - { src: '{{pl_hosts}}_hosts.j2',dest: '/etc/hosts' }
  tags: Config Hosts