- name: Plat Limits 
  lineinfile: 
    dest: /etc/security/limits.conf
    insertbefore: '# End of file' 
    line: '{{item}}' 
    state: present 
    backup: yes    
  with_items:
    - '{{pl_config_user}}     hard   nproc   {{pl_hard_nproc}}'
    - '{{pl_config_user}}     soft   nproc   {{pl_soft_nproc}}'
    - '{{pl_config_user}}     hard   nofile  {{pl_hard_nofile}}'
    - '{{pl_config_user}}     soft   nofile  {{pl_soft_nofile}}'
    - '{{pl_config_user}}     hard   memlock {{pl_hard_memlock}}'
    - '{{pl_config_user}}     soft   memlock {{pl_soft_memlock}}'
 
- name: Plat Ulimit 
  lineinfile:
    dest: /etc/rc.local
    regexp: 'ulimit -s unlimited'
    backrefs: no
    line: 'ulimit -s unlimited'

- name: Plat Sysctl
  sysctl:
    name:  '{{item.name}}'
    value: '{{item.value}}'
    sysctl_set: yes
    state: '{{item.state}}'
    reload: yes
  with_items:
    - { name: 'vm.swappiness',       value: '{{pl_vm_swappiness}}',          state: present }
    - { name: 'vm.max_map_count',    value: '{{pl_vm_max_map_count}}',       state: present }
    - { name: 'vm.overcommit_memory',value: '{{pl_vm_overcommit_memory}}',   state: present }
    - { name: 'net.core.somaxconn',  value: '{{pl_net_core_somaxconn}}',     state: present }

- name: Plat Kernel_THP Enforece Hostname 
  shell: '{{item}}'
  with_items:
    - 'echo "{{pl_transparent_hugepage}}" > /sys/kernel/mm/transparent_hugepage/enabled'
    #- 'setenforce 0'
    - 'hostname {{pl_hostname}}'
    - 'ulimit -s unlimited'