- name: Kafka Source Packages
  unarchive: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - { src: 'kafka_{{pl_kafka_version}}.tgz'         ,dest: '{{pl_kafka_home}}/kafka' }

- name: JDK Check
  stat: path='{{pl_kafka_home}}/kafka/jdk{{pl_jdk_version}}/bin/java'
  register: jdk

- import_tasks: jdk.yml
  when: jdk.stat.exists == False
 
- name: Kafka Config
  template: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - { src: 'server.properties.j2',dest: '{{pl_kafka_home}}/kafka/kafka_{{pl_kafka_version}}/config/server.properties' }
    - { src: 'kafka.service.j2',    dest: '/lib/systemd/system/kafka.service' }