#下载nginx源码包
- name: 获取Nginx安装文件
  get_url:
    url: "{{item}}"
    dest: /home/deploy
    timeout: 30
  with_items:
    - 'https://nginx.org/download/nginx-{{pl_nginx_version}}.tar.gz'
    - 'https://ftp.pcre.org/pub/pcre/pcre-{{pl_pcre_version}}.tar.gz'
    - 'https://www.zlib.net/zlib-{{pl_zlib_version}}.tar.gz'
    - 'https://www.openssl.org/source/openssl-{{pl_openssl_version}}.tar.gz'
    - 'https://github.com/simplresty/ngx_devel_kit/archive/v{{pl_ngx_devel_kit_version}}.tar.gz'
    - 'https://github.com/openresty/lua-nginx-module/archive/v{{pl_lua_nginx_module_version}}.tar.gz'
    - 'https://github.com/nbs-system/naxsi/archive/{{pl_naxsi_version}}.tar.gz'
    - 'https://github.com/jemalloc/jemalloc/archive/{{pl_jemalloc_version}}.tar.gz'
    - 'https://github.com/openresty/luajit2/archive/v{{pl_luajit2_version}}.tar.gz'
    - 'https://github.com/arut/nginx-dav-ext-module/archive/v{{pl_nginx_dav_ext_module_version}}.tar.gz'