#path
pl_home :        "{{home|default('/data')}}"
pl_deploy_home : "{{deploy_home|default('/home/deploy')}}"
#user
pl_user : "{{user|default('redis')}}"
pl_uid :  "{{uid|default('6379')}}"
pl_group: "{{group|default('redis')}}"
pl_gid:   "{{gid|default('6379')}}"
#install
pl_redis_version: "{{redis_version|default('3.2.12')}}"
pl_redis_port :   "{{redis_port|default('6379')}}"
pl_redis_pwd :    "{{redis_pwd|default('123456')}}"
