- import_tasks: mysql_prepare.yml
  tags:
    - mysql_prepare
  
- import_tasks: mysql_install.yml
  tags:
    - mysql_install
    
- import_tasks: mysql_config.yml
  tags:
    - mysql_config
    
- import_tasks: mysql_grant.yml
  tags:
    - mysql_grant