- name: MySQL Group
  group: 
    name: '{{pl_mysql_group}}' 
    gid:  '{{pl_mysql_gid}}'

- name: MySQL User
  user: 
    name:  '{{pl_mysql_user}}'
    group: '{{pl_mysql_group}}'    
    uid:   '{{pl_mysql_uid}}'
    home:  '{{pl_mysql_home}}/mysql'    
    shell: /bin/bash

- name: MySQL Floder
  file: 
    path:  '{{item.path}}' 
    owner: '{{item.owner}}' 
    group: '{{item.group}}' 
    mode: 0755
    state: '{{item.state}}'
  with_items:
    - { path: '{{pl_deploy_home}}/support',           owner: 'root',             group: 'root',              state: directory }
    - { path: '{{pl_mysql_home}}/mysql/etc',          owner: '{{pl_mysql_user}}',group: '{{pl_mysql_group}}',state: directory }
    - { path: '{{pl_mysql_home}}/mysql/data',         owner: '{{pl_mysql_user}}',group: '{{pl_mysql_group}}',state: directory }
    - { path: '{{pl_mysql_home}}/mysql/pid',          owner: '{{pl_mysql_user}}',group: '{{pl_mysql_group}}',state: directory }
    - { path: '{{pl_mysql_home}}/mysql/log',          owner: '{{pl_mysql_user}}',group: '{{pl_mysql_group}}',state: directory }
    - { path: '{{pl_mysql_home}}/mysql/binlog',       owner: '{{pl_mysql_user}}',group: '{{pl_mysql_group}}',state: directory }   
    - { path: '{{pl_mysql_home}}/mysql/sock',         owner: '{{pl_mysql_user}}',group: '{{pl_mysql_group}}',state: directory }
    - { path: '{{pl_mysql_home}}/mysql/log/mysql.log',owner: '{{pl_mysql_user}}',group: '{{pl_mysql_group}}',state: touch }
    - { path: '/etc/my.cnf',                          owner: 'root',             group: 'root',              state: absent }
