- name: Jemalloc Check
  stat: path=/usr/local/lib/libjemalloc.so.2
  register: jemalloc
  
- import_tasks: jemalloc.yml
  when: jemalloc.stat.exists == false
    
- name: MySQL Source Package
  unarchive: src=mysql-{{pl_mysql_version}}.tar.gz dest={{pl_deploy_home}}

- name: MySQL Compile Str
  set_fact:
    mysql_compile_str: "{{ mysql_compile_str | default('') }} {{ '-D' + item.option + '=' + item.value }}"
  with_items:
    - "{{ mysql_compile }}"  
    
- name: MySQL Install Configure  
  command: cmake . {{ mysql_compile_str }}
  args:
    chdir: '{{pl_deploy_home}}/mysql-{{pl_mysql_version}}'

- name: MySQL Install
  make:
    chdir: '{{pl_deploy_home}}/mysql-{{pl_mysql_version}}'
    target: install
    params:
      NUM_THREADS: 4 