- name: MySQL Configure
  template: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - { src: 'my.cnf.j2',        dest: '{{pl_mysql_home}}/mysql/etc/my.cnf' }
    - { src: 'mysqld.service.j2',dest: '/usr/lib/systemd/system/mysqld.service' }
    
- name: MySQL Initialization DB
  command: ./mysql_install_db --user={{pl_mysql_user}} --basedir={{pl_mysql_home}}/mysql/mysql --datadir={{pl_mysql_home}}/mysql/data
  args:
    chdir: '{{pl_mysql_home}}/mysql/mysql/scripts'

- name: MySQL Bin Service
  file: src='{{item.src}}' dest='{{item.dest}}' state=link
  with_items:
    - { src: '{{pl_mysql_home}}/mysql/mysql/bin/mysql',                 dest: '/usr/bin/mysql' }
    - { src: '{{pl_mysql_home}}/mysql/mysql/bin/mysqladmin',            dest: '/usr/bin/mysqladmin' }
    - { src: '{{pl_mysql_home}}/mysql/mysql/bin/mysqldump',             dest: '/usr/bin/mysqldump' }
    - { src: '{{pl_mysql_home}}/mysql/mysql/bin/mysqlbinlog',           dest: '/usr/bin/mysqlbinlog' }
    - { src: '{{pl_mysql_home}}/mysql/mysql/support-files/mysql.server',dest: '/etc/init.d/mysqld-server' } 
    
- name: MySQL Firewall
  firewalld: port={{pl_mysql_port}}/tcp permanent=true state=enabled
  
- name: change floder owner
  file: path='{{pl_mysql_home}}/mysql' owner='{{pl_mysql_user}}' group='{{pl_mysql_group}}' recurse=yes
  
- name: MySQL start
  systemd: name='{{item.name}}' state='{{item.state}}' enabled=yes
  with_items:
    - { name: 'firewalld',state: 'reloaded' }
    - { name: 'mysqld',   state: 'started' }