- name: Squid Group | 创建squid属组
  group: 
    name: '{{pl_squid_user}}' 
    gid:  '{{pl_squid_id}}'

- name: Squid User | 创建squid用户
  user: 
    name:  '{{pl_squid_user}}'
    group: '{{pl_squid_user}}'
    uid:   '{{pl_squid_id}}'
    shell: /bin/bash

- name: Squid Clean Other Version | 清楚预装squid
  yum: name=squid state=absent

- name: Squid Floder |创建squid目录
  file: 
    path:  '{{item}}'
    mode: 0755
    state: 'directory'
  with_items:
    - '{{pl_deploy_home}}'
    - '{{pl_squid_home}}'
    - '{{pl_squid_home}}/{{pl_role_type}}'
    - '{{pl_squid_home}}/{{pl_role_type}}/{{pl_server_type}}'
    - '{{pl_squid_home}}/{{pl_role_type}}/{{pl_server_type}}/log'
    - '{{pl_squid_home}}/{{pl_role_type}}/{{pl_server_type}}/run'
    - '{{pl_squid_home}}/{{pl_role_type}}/{{pl_server_type}}/etc'
    - '{{pl_squid_home}}/{{pl_role_type}}/{{pl_server_type}}/var'
 