- name: add group for redis
  group: 
    name: '{{group}}' 
    gid: '{{gid}}'

- name: add user for redis
  user: 
    name: '{{user}}'
    group: '{{group}}'    
    uid: '{{uid}}' 
    home: '{{home}}' 
    shell: /bin/bash

- name: make floder for use 
  file: 
    path: '{{item.path}}' 
    owner: '{{item.owner}}' 
    group: '{{item.group}}' 
    mode: 0755 
    state: directory
  with_items:
    - { path: '{{deploy_home}}/support',owner: 'root',group: 'root' }
    - { path: '{{home}}',owner: '{{user}}',group: '{{group}}' }
    - { path: '{{home}}/redis',owner: '{{user}}',group: '{{group}}' }
    - { path: '{{home}}/redis/data',owner: '{{user}}',group: '{{group}}' }
    - { path: '{{home}}/redis/etc',owner: '{{user}}',group: '{{group}}' }
    - { path: '{{home}}/redis/bin',owner: '{{user}}',group: '{{group}}' }
    - { path: '{{home}}/redis/pid',owner: '{{user}}',group: '{{group}}' }
    - { path: '{{home}}/redis/log',owner: '{{user}}',group: '{{group}}' }
    
- name: extract redis source packages
  unarchive: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - { src: 'redis-{{redis_version}}.tar.gz',dest: '{{deploy_home}}' }

- name: make redis test
  make:
    chdir: '{{deploy_home}}/redis-{{redis_version}}'
    target: test
 
- name: make redis install
  make:
    chdir: '{{deploy_home}}/redis-{{redis_version}}/src'
    target: install 
    
- name: copy redis bin
  copy: src='{{item.src}}' dest='{{item.dest}}' remote_src=yes mode=755
  with_items:
    - { src: '{{deploy_home}}/redis-{{redis_version}}/src/redis-benchmark',dest: '{{home}}/redis/bin/redis-benchmark' }
    - { src: '{{deploy_home}}/redis-{{redis_version}}/src/redis-check-aof',dest: '{{home}}/redis/bin/redis-check-aof' }
    - { src: '{{deploy_home}}/redis-{{redis_version}}/src/redis-check-rdb',dest: '{{home}}/redis/bin/redis-check-rdb' }
    - { src: '{{deploy_home}}/redis-{{redis_version}}/src/redis-cli',dest: '{{home}}/redis/bin/redis-cli' }
    - { src: '{{deploy_home}}/redis-{{redis_version}}/src/redis-sentinel',dest: '{{home}}/redis/bin/redis-sentinel' }
    - { src: '{{deploy_home}}/redis-{{redis_version}}/src/redis-server',dest: '{{home}}/redis/bin/redis-server' }

- name: copy redis cli
  file: src='{{home}}/redis/bin/redis-cli' dest='/usr/bin/redis-cli' state=link
  
- name: config redis
  template: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - { src: 'redis.conf.j2',dest: '{{home}}/redis/etc/redis.conf' }
    - { src: 'redis-server.service.j2',dest: '/lib/systemd/system/redis-server.service' }  

- name: fire wall redis
  firewalld: port={{redis_port}}/tcp permanent=true state=enabled
  
- name: change floder owner
  file: path='{{home}}/redis' owner='{{user}}' group='{{group}}' recurse=yes  

- name: start redis
  systemd: name='{{item.name}}' state='{{item.state}}' enabled=yes
  with_items:
    - { name: 'firewalld',state: 'reloaded' }
    - { name: 'redis-server',state: 'started' }