- name: Redis Source Package
  unarchive: src='redis-{{pl_redis_version}}.tar.gz' dest='{{pl_deploy_home}}'

- name: Redis Make Test
  make:
    chdir: '{{pl_deploy_home}}/redis-{{pl_redis_version}}'
    target: test
    params:
      NUM_THREADS: 4
  ignore_errors: yes
 
- name: Redis Make Install
  make:
    chdir: '{{pl_deploy_home}}/redis-{{pl_redis_version}}/src'
    target: install
    params:
      NUM_THREADS: 4 
  ignore_errors: yes   