- name: Redis Group
  group: 
    name: '{{pl_redis_group}}' 
    gid:  '{{pl_redis_gid}}'

- name: Redis User
  user: 
    name:  '{{pl_redis_user}}'
    group: '{{pl_redis_group}}'    
    uid:   '{{pl_redis_uid}}' 
    home:  '{{pl_redis_home}}/redis'    
    shell: /bin/bash

- name: Redis Floder 
  file: 
    path: '{{item.path}}' 
    owner: '{{item.owner}}' 
    group: '{{item.group}}' 
    mode: 0755 
    state: directory
  with_items:
    - { path: '{{pl_deploy_home}}',          owner: 'root',             group: 'root' }
    - { path: '{{pl_redis_home}}/redis',     owner: '{{pl_redis_user}}',group: '{{pl_redis_group}}' }
    - { path: '{{pl_redis_home}}/redis/data',owner: '{{pl_redis_user}}',group: '{{pl_redis_group}}' }
    - { path: '{{pl_redis_home}}/redis/etc', owner: '{{pl_redis_user}}',group: '{{pl_redis_group}}' }
    - { path: '{{pl_redis_home}}/redis/bin', owner: '{{pl_redis_user}}',group: '{{pl_redis_group}}' }
    - { path: '{{pl_redis_home}}/redis/pid', owner: '{{pl_redis_user}}',group: '{{pl_redis_group}}' }
    - { path: '{{pl_redis_home}}/redis/log', owner: '{{pl_redis_user}}',group: '{{pl_redis_group}}' }