#!/bin/bash

color(){
if [ "`systemctl status $1 |grep Active|awk '{print $3}'`" = "(running)" ];then &>/dev/null
        POINT="\033[32m\033[1m● "
else
        POINT="\033[31m\033[5m\033[1m● "
fi
MESAGE=`systemctl status $1 |grep Active`
PID=`systemctl status $1 | grep "Main PID"`
}

service_start(){
}

service_status(){
}

service_stop(){
}

service_restart(){
}

case "$1" in
    start)
        service_start
    ;;
    stop)
        service_stop
    ;;
    restart)
        service_restart
    ;;
    status)
        service_status
    ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status}"
    ;;
esac
