- name: Plat Node Source Packages
  unarchive: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - { src: 'node-v{{pl_node_version}}-linux-x64.tar.gz' ,dest: '{{pl_node_home}}' }
    - { src: 'node-ui-{{pl_node_ui_version}}.tar.gz'      ,dest: '{{pl_node_home}}' }
    - { src: 'node-log-srv-{{pl_node_log_version}}.tar.gz',dest: '{{pl_node_home}}' }
    - { src: 'node-config-{{pl_node_conf_version}}.tar.gz',dest: '{{pl_node_home}}' }
    - { src: 'web4node-{{pl_node_web_version}}.tar.gz'    ,dest: '{{pl_node_home}}' }

- name: Plat Node_bin
  file: 
    src:  '{{item.src}}' 
    dest: '{{item.dest}}' 
    state: 'link'
  with_items:
    - { src: '{{pl_node_home}}/node-v{{pl_node_version}}-linux-x64/bin/node',dest: '/bin/node' }
    - { src: '{{pl_node_home}}/node-v{{pl_node_version}}-linux-x64/bin/npm', dest: '/bin/npm' }
    - { src: '{{pl_node_home}}/web4node/public/t/paas/0function',            dest: '{{pl_node_home}}/web4node/private' }
    - { src: '{{pl_node_home}}/change_logdb',                                dest: '{{pl_node_home}}/web4node/change_logdb' } 
    
- name: Plat Node Floder Owner
  file: path='{{item}}/' owner='{{pl_node_user}}' group='{{pl_node_group}}' recurse=yes
  with_items:
    - '{{pl_node_home}}/node-v{{pl_node_version}}-linux-x64'
    - '{{pl_node_home}}/node-ui'
    - '{{pl_node_home}}/node-log-srv'
    - '{{pl_node_home}}/node-config'
    - '{{pl_node_home}}/web4node'