- name: Plat Node Source Packages | 解压平台node软件包
  unarchive: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - { src: 'node-v{{pl_node_version}}-linux-x64.tar.gz' ,dest: '{{pl_squid_home}}/{{pl_role_type}}' }
    - { src: 'node-ui-{{pl_node_ui_version}}.tar.gz'      ,dest: '{{pl_squid_home}}/{{pl_role_type}}' }
    - { src: 'node-log-srv-{{pl_node_log_version}}.tar.gz',dest: '{{pl_squid_home}}/{{pl_role_type}}' }
    - { src: 'node-config-{{pl_node_conf_version}}.tar.gz',dest: '{{pl_squid_home}}/{{pl_role_type}}' }
    - { src: 'web4node-{{pl_node_web_version}}.tar.gz'    ,dest: '{{pl_squid_home}}/{{pl_role_type}}' }

- name: Plat Node_bin | 为node执行程序建立软连接
  file: 
    src:  '{{item.src}}' 
    dest: '{{item.dest}}' 
    state: 'link'
  with_items:
    - { src: '{{pl_squid_home}}/{{pl_role_type}}/node-v{{pl_node_version}}-linux-x64/bin/node',dest: '/bin/node' }
    - { src: '{{pl_squid_home}}/{{pl_role_type}}/node-v{{pl_node_version}}-linux-x64/bin/npm', dest: '/bin/npm' }
    - { src: '{{pl_squid_home}}/{{pl_role_type}}/web4node/public/t/paas/0function',            dest: '{{pl_squid_home}}/{{pl_role_type}}/web4node/private' }
    - { src: '{{pl_squid_home}}/{{pl_role_type}}/change_logdb',                                dest: '{{pl_squid_home}}/{{pl_role_type}}/web4node/change_logdb' } 
    
- name: Plat Node Floder Owner | 修改node文件夹用户
  file: path='{{item}}/' owner='{{pl_node_user}}' group='{{pl_node_user}}' recurse=yes
  with_items:
    - '{{pl_squid_home}}/{{pl_role_type}}/node-v{{pl_node_version}}-linux-x64'
    - '{{pl_squid_home}}/{{pl_role_type}}/node-ui'
    - '{{pl_squid_home}}/{{pl_role_type}}/node-log-srv'
    - '{{pl_squid_home}}/{{pl_role_type}}/node-config'
    - '{{pl_squid_home}}/{{pl_role_type}}/web4node'