#user
pl_user : "{{user|default('www')}}"
pl_uid :  "{{uid|default('80')}}"
pl_group: "{{group|default('www')}}"
pl_gid :  "{{gid|default('80')}}"
#path
pl_home :        "{{home|default('/data')}}"
pl_deploy_home : "{{deploy_home|default('/home/deploy')}}"
#version
pl_nginx_version :   "{{nginx_version|default('1.14.2')}}"
pl_pcre_version :    "{{pcre_version|default('8.42')}}"
pl_zlib_version :    "{{zlib_version|default('1.2.11')}}"
pl_openssl_version : "{{openssl_version|default('1.1.1a')}}"
pl_lua_nginx_module_version : "{{lua_nginx_module_version|default('0.10.13')}}"
pl_luajit2_version :          "{{luajit2_version|default('2.1-20190115')}}"
pl_ngx_devel_kit_version :    "{{ngx_devel_kit_version|default('0.3.1rc1')}}"
pl_jemalloc_version : "{{jemalloc_version|default('5.1.0')}}"
pl_naxsi_version :    "{{naxsi_version|default('0.56')}}"
#personal
pl_custom_server :   "{{custom_server|default('MyServer')}}"
pl_custom_version :  "{{custom_version|default('8888')}}"
pl_trs_host :        "{{trs_host|default('localhost')}}"
pl_druid_host :      "{{druid_host|default('localhost')}}"
pl_dscore_host :     "{{dscore_host|default('localhost')}}"
pl_empi_host :       "{{empi_host|default('localhost')}}"
pl_node_host :       "{{node_host|default('localhost')}}"
pl_img_server_host : "{{img_server_host|default('localhost')}}"
#install config
nginx_compile:
  - { option: "prefix",                     value: "{{pl_home}}/nginx" }
  - { option: "sbin-path",                  value: "{{pl_home}}/nginx/sbin/nginx" }
  - { option: "conf-path",                  value: "{{pl_home}}/nginx/conf/nginx.conf" }
  - { option: "error-log-path",             value: "{{pl_home}}/nginx/logs/error.log" }
  - { option: "pid-path",                   value: "{{pl_home}}/nginx/nginx.pid" }
  - { option: "lock-path",                  value: "{{pl_home}}/nginx/nginx.lock" }
  - { option: "user",                       value: "{{pl_user}}" }
  - { option: "group",                      value: "{{pl_group}}" }
  - { option: "http-client-body-temp-path", value: "{{pl_home}}/nginx/client_body " }
  - { option: "http-proxy-temp-path",       value: "{{pl_home}}/nginx/proxy" }
  - { option: "http-fastcgi-temp-path",     value: "{{pl_home}}/nginx/fastcgi" }
  - { option: "http-uwsgi-temp-path",       value: "{{pl_home}}/nginx/uwsgi" }
  - { option: "http-scgi-temp-path",        value: "{{pl_home}}/nginx/scgi" }

nginx_mode:
  - http_ssl_module  
  - http_ssl_module  
  - http_v2_module  
  - http_dav_module  
  - http_flv_module  
  - http_mp4_module  
  - http_realip_module  
  - http_addition_module  
  - http_xslt_module  
  - http_stub_status_module  
  - http_sub_module  
  - http_random_index_module  
  - http_degradation_module  
  - http_secure_link_module  
  - http_gzip_static_module  
  - http_perl_module  
  - file-aio  
  - mail  
  - mail_ssl_module  
  - http_image_filter_module    
  - debug
  - stream
  - pcre-jit
  
nginx_lib:
  - { option: "pcre",                value: "{{pl_deploy_home}}/pcre-{{pl_pcre_version}}" }   
  - { option: "zlib",                value: "{{pl_deploy_home}}/zlib-{{pl_zlib_version}}" } 
  - { option: "openssl",             value: "{{pl_deploy_home}}/openssl-{{pl_openssl_version}}" }     
  - { option: "http_geoip_module",   value: "dynamic" }   
  - { option: "stream_geoip_module", value: "dynamic" }  

nginx_ex:  
  - "-Wl,-rpath,/usr/local/lib"
  - "/usr/local/lib/libjemalloc.so.2"

nginx_ex_moudle:
  - "{{pl_deploy_home}}/naxsi-{{pl_naxsi_version}}/naxsi_src"
  - "{{pl_deploy_home}}/ngx_devel_kit-{{pl_ngx_devel_kit_version}}"
  - "{{pl_deploy_home}}/lua-nginx-module-{{pl_lua_nginx_module_version}}"