#zabbix
- name: Zabbix Agent Conf | 生成zabbix-agent配置文件
  template:
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
    backup: yes
  with_items:
    - { src: 'zabbix_agentd.conf.j2', dest: '{{pl_zabbix_agent_home}}/zabbix/etc/zabbix_agentd.conf' }

#nginx
- name: Zabbix Agent Conf Nginx Check | 检查是否安装nginx
  stat:
    path: '/usr/lib/systemd/system/nginx.service'
  register: nginx

- name: Zabbix Agent Conf Nginx | 配置nginx监控
  template:
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
    backup: yes
  with_items:
    - { src: 'config/nginx.conf.j2',dest: '{{pl_zabbix_agent_home}}/zabbix/etc/zabbix_agentd.conf.d/nginx.conf' } 
    - { src: 'scripts/nginx.sh.j2', dest: '{{pl_zabbix_agent_home}}/zabbix/scripts/nginx.sh' }
  when: nginx.stat.exists == True

#mysql
- name: Zabbix Agent Conf Mysql Check | 检查是否安装mysql
  stat:
    path: '/usr/lib/systemd/system/mysqld.service'
  register: mysql

- name: Zabbix Agent Conf Mysql | 配置mysql监控
  template:
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
    backup: yes
  with_items:
    - { src: 'config/mysql.conf.j2',  dest: '{{pl_zabbix_agent_home}}/zabbix/etc/zabbix_agentd.conf.d/mysql.conf' } 
    - { src: 'scripts/mysql.sh.j2',   dest: '{{pl_zabbix_agent_home}}/zabbix/scripts/mysql.sh' }
    - { src: 'scripts/.mysql.pwd.j2', dest: '{{pl_zabbix_agent_home}}/zabbix/scripts/.mysql.pwd' }
  when: mysql.stat.exists == True
  
#dscore
- name: Zabbix Agent Conf Dscore Check | 检查是否安装dscore
  stat:
    path: '/usr/lib/systemd/system/dscore.service'
  register: dscore

- name: Zabbix Agent Conf Dscore | 配置dscore监控
  template:
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
    backup: yes
  with_items:
    - { src: 'config/dscore.conf.j2',dest: '{{pl_zabbix_agent_home}}/zabbix/etc/zabbix_agentd.conf.d/dscore.conf' } 
    - { src: 'scripts/dscore.sh.j2', dest: '{{pl_zabbix_agent_home}}/zabbix/scripts/dscore.sh' }
  when: dscore.stat.exists == True
  
#redis
- name: Zabbix Agent Conf Redis Check | 检查是否安装redis
  stat:
    path: '/usr/lib/systemd/system/redis-server.service'
  register: redis

- name: Zabbix Agent Conf Redis | 配置redis监控
  template:
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
    backup: yes
  with_items:
    - { src: 'config/redis.conf.j2',  dest: '{{pl_zabbix_agent_home}}/zabbix/etc/zabbix_agentd.conf.d/redis.conf' } 
    - { src: 'scripts/redis.sh.j2',   dest: '{{pl_zabbix_agent_home}}/zabbix/scripts/redis.sh' }
    - { src: 'scripts/.redis.pwd.j2', dest: '{{pl_zabbix_agent_home}}/zabbix/scripts/.redis.pwd' }
  when: redis.stat.exists == True

#kafka
- name: Zabbix Agent Conf Kafka Check | 检查是否安装kafka
  stat:
    path: '/usr/lib/systemd/system/kafka.service'
  register: kafka

- name: Zabbix Agent Conf Kafka | 配置kafka监控
  template:
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
    backup: yes
  with_items:
    - { src: 'config/kafka.conf.j2',dest: '{{pl_zabbix_agent_home}}/zabbix/etc/zabbix_agentd.conf.d/kafka.conf' } 
    - { src: 'scripts/kafka.sh.j2', dest: '{{pl_zabbix_agent_home}}/zabbix/scripts/kafka.sh' }
  when: kafka.stat.exists == True
  
#zookeeper
- name: Zabbix Agent Conf Zookeeper Check | 检查是否安装zookeeper
  stat:
    path: '/usr/lib/systemd/system/zookeeper.service'
  register: zookeeper

- name: Zabbix Agent Conf Zookeeper | 配置zookeeper监控
  template:
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
    backup: yes
  with_items:
    - { src: 'config/zookeeper.conf.j2',dest: '{{pl_zabbix_agent_home}}/zabbix/etc/zabbix_agentd.conf.d/zookeeper.conf' } 
    - { src: 'scripts/zookeeper.sh.j2', dest: '{{pl_zabbix_agent_home}}/zabbix/scripts/zookeeper.sh' }
  when: zookeeper.stat.exists == True