- name: Tomcat JDK Source Package | 解压jdk源码包
  unarchive: 
    src:     'jdk/jdk-{{pl_jdk_version}}-linux-x64.tar.gz' 
    dest:    '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}'

- name: Tomcat JDK Floder Owner | 修改jdk用户
  file: 
    path:  '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}/jdk{{pl_jdk_version}}' 
    owner: '{{pl_tomcat_user}}'
    group: '{{pl_tomcat_user}}'
    recurse: yes