- name: Zabbix JDK Source Package
  unarchive: 
    src:     '{{item.src}}' 
    dest:    '{{item.dest}}'
    owner:   '{{pl_zabbix_agent_user}}' 
    group:   '{{pl_zabbix_agent_group}}'
  with_items:
    - { src: 'jdk-{{pl_jdk_version}}-linux-x64.tar.gz', dest: '{{pl_zabbix_agent_home}}/zabbix' }

- name: Zabbix JDK Floder Owner
  file: 
    path:  '{{item.path}}' 
    owner: '{{pl_zabbix_agent_user}}' 
    group: '{{pl_zabbix_agent_group}}' 
    recurse: yes
  with_items:
    - { path: '{{pl_zabbix_agent_home}}/zabbix/jdk{{pl_jdk_version}}' }

- name: Zabbix JDK Env
  lineinfile:
    path: '{{pl_zabbix_agent_home}}/zabbix/.bash_profile'
    line: '{{item}}'
    insertbefore: 'export PATH'
  with_items:  
  - '#set java environment'
  - 'JAVA_HOME={{pl_zabbix_agent_home}}/zabbix/jdk{{pl_jdk_version}}'
  - 'JRE_HOME=$JAVA_HOME/jre'
  - 'PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin'
  - 'CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib'
  - 'export JAVA_HOME JRE_HOME PATH CLASSPATH'