- name: Zabbix Agent Systemd | 将zabbix-agent加入系统服务
  template:
    src:  'zabbix-agent.service.j2'
    dest: '/usr/lib/systemd/system/zabbix-agent.service'
 
- name: Zabbix Floder Owner | 修改 zabbix-agent目录用户
  file: 
    path:  '{{pl_zabbix_agent_home}}/zabbix' 
    owner: '{{pl_zabbix_agent_user}}' 
    group: '{{pl_zabbix_agent_user}}' 
    recurse: yes  
    
- name: Zabbix Firewall | 为zabbix-agent开放防火墙限制
  firewalld: 
    port: '{{pl_zabbix_agent_port}}/tcp'
    permanent: true 
    state: enabled

- name: Zabbix Agent Start | 启动zabbix-agent
  systemd: 
    name:  '{{item.name}}'
    state: '{{item.state}}'
    enabled: yes
  with_items:
    - { name: 'firewalld',    state: 'reloaded' }
    - { name: 'zabbix-agent', state: 'started' }