- name: Plat Node Service | 将node加入系统服务
  template: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - { src: 'node-ui.service.j2',     dest: '/lib/systemd/system/node-ui.service' }
    - { src: 'node-log-srv.service.j2',dest: '/lib/systemd/system/node-log-srv.service' }

- name: Plat Node Firewall | 为node开放防火墙限制
  firewalld: port={{item}}/tcp permanent=true state=enabled
  with_items:
    - '{{pl_node_port}}'
    - 8012
    - 8013
    - 8014
    - 8016
    - 8017
    
- name: Plat Node Start | 启动node
  systemd: name='{{item.name}}' state='{{item.state}}' enabled=yes
  with_items:
    - { name: 'node-ui',     state: 'started' }
    - { name: 'node-log-srv',state: 'started' }
    - { name: 'firewalld',   state: 'reloaded' }