- name: Tomcat Firewall | 防火墙开放tomcat服务端口
  firewalld: 
    port: '{{pl_tomcat_port}}/tcp'
    permanent: true 
    state: enabled
  
- name: Tomcat Floder Owner | 变更tomcat目录所有者
  file: 
    path:  '{{item}}' 
    owner: '{{pl_tomcat_user}}' 
    group: '{{pl_tomcat_user}}' 
    recurse: yes
  with_items:
    - '{{pl_tomcat_home}}/{{pl_role_type}}/{{pl_server_type}}'
    
- name: Tomcat Start | 启动tomcat
  systemd: 
    name:  '{{item.name}}' 
    state: '{{item.state}}' 
    enabled: yes
  with_items:
    - { name: 'firewalld',          state: 'reloaded' }
    - { name: '{{pl_server_type}}', state: 'restarted' }