- name: Solr Group | 创建solr属组
  group: 
    name: '{{pl_solr_user}}'
    gid:  '{{pl_solr_id}}'

- name: Solr User | 创建solr用户
  user: 
    name:  '{{pl_solr_user}}'
    group: '{{pl_solr_user}}'
    uid:   '{{pl_solr_id}}'
    shell: /bin/bash

- name: Solr Floder | 创建solr目录
  file: 
    path: '{{item}}'
    mode: 0755
    state: directory
  with_items:
    - '{{pl_solr_home}}/{{pl_role_type}}/{{pl_server_type}}'
    - '{{pl_solr_home}}/{{pl_role_type}}/{{pl_server_type}}/log'
    - '{{pl_solr_home}}/{{pl_role_type}}/{{pl_server_type}}/pid'

#jdk   
- name: Solr JDK Check | jdk检查
  stat: 
    path: '{{pl_solr_home}}/{{pl_role_type}}/{{pl_server_type}}/jdk{{pl_jdk_version}}'
  register: jdk

- import_tasks: jdk.yml
  when: jdk.stat.exists == False

- name: Solr Source Packages | 解压solr软件包
  unarchive: 
    src:  'solr-{{pl_solr_version}}.tgz' 
    dest: '{{pl_solr_home}}/{{pl_role_type}}/{{pl_server_type}}'
    
- name: Solr Server Link | 为server创建软连接
  file: 
    src:  '{{pl_solr_home}}/{{pl_role_type}}/{{pl_server_type}}/solr-{{pl_solr_version}}/server' 
    dest: '{{pl_solr_home}}/{{pl_role_type}}/{{pl_server_type}}/server' 
    state: 'link'
    
- name: Solr Floder Owner | 改变solr目录地址
  file: 
    path:  '{{pl_solr_home}}/{{pl_role_type}}/{{pl_server_type}}'
    owner: '{{pl_solr_user}}' 
    group: '{{pl_solr_user}}' 
    recurse: yes

- name: Solr Service | 将solr加入系统服务并生成环境文件
  template: 
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
  with_items:
    - { src: 'solr.service.j2', dest: '/usr/lib/systemd/system/solr.service' }
    - { src: 'solr.in.sh.j2',   dest: '{{pl_solr_home}}/{{pl_role_type}}/{{pl_server_type}}/solr-{{pl_solr_version}}/bin/solr.in.sh' }

- name: Solr Firewall | 将solr 服务端口加入防火墙
  firewalld: 
    port: '{{pl_solr_port}}/tcp'
    permanent: true
    state: enabled

- name: Solr Start | 启动solr
  systemd: 
    name:  '{{item.name}}' 
    state: '{{item.state}}' 
    enabled: yes
  with_items:
    - { name: 'firewalld',state: 'reloaded' }
    - { name: 'solr',     state: 'started' }

- name: Solr Wait | 等待solr服务启动完成
  wait_for:
    port: '{{pl_solr_port}}'
    state: started
    delay: 10
    timeout: 120

- name: Solr Create Core | 创建solr core
  command: ./solr create -c empi
  args:
    chdir: '{{pl_solr_home}}/{{pl_role_type}}/{{pl_server_type}}/solr-{{pl_solr_version}}/bin/'
  become: true
  become_user: solr

- name: Solr Core Data Link | 为core data创建软连接
  file: 
    src:  '{{pl_solr_home}}/{{pl_role_type}}/{{pl_server_type}}/solr-{{pl_solr_version}}/server/solr/{{pl_solr_core}}/data' 
    dest: '{{pl_solr_home}}/{{pl_role_type}}/{{pl_server_type}}/data' 
    state: 'link'