- name: PLAT MySQL Group | 创建mysql属组
  group: 
    name: '{{pl_mysql_user}}' 
    gid:  '{{pl_mysql_id}}'

- name: PLAT MySQL User | 创建mysql用户
  user: 
    name:  '{{pl_mysql_user}}'
    group: '{{pl_mysql_user}}'    
    uid:   '{{pl_mysql_id}}'
    shell: /bin/bash

- name: PLAT MySQL Floder | 创建mysql目录
  file: 
    path:  '{{item.path}}' 
    mode: 0755
    state: '{{item.state}}'
  with_items:
    - { path: '{{pl_deploy_home}}',                                                 state: directory }
    - { path: '{{pl_mysql_home}}',                                                  state: directory }
    - { path: '{{pl_mysql_home}}/{{pl_role_type}}',                                 state: directory }
    - { path: '{{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}',              state: directory }
    - { path: '{{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}/etc',          state: directory }
    - { path: '{{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}/data',         state: directory }
    - { path: '{{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}/pid',          state: directory }
    - { path: '{{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}/log',          state: directory }
    - { path: '{{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}/binlog',       state: directory }   
    - { path: '{{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}/sock',         state: directory }
    - { path: '{{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}/log/mysql.log',state: touch }
    - { path: '/etc/my.cnf',                                                        state: absent }
