- name: PLAT MySQL Starting | 等待mysql启动
  wait_for:
    port: '{{pl_mysql_port}}'
    delay: 10
    state: present

- name: PLAT MySQL Grant | 创建mysql授权用户
  mysql_user: 
    name: '{{item.name}}'
    password: '{{item.password}}'
    priv: '*.*:ALL'
    host: '{{item.host}}'
    state: present
    login_user: 'root'
    login_unix_socket: '{{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}/sock/mysql.sock'   
  with_items:
     - { name: '{{pl_mysql_db_user}}',password: '{{pl_mysql_db_pwd}}',  host: '%' }
     - { name: '{{pl_mysql_db_user}}',password: '{{pl_mysql_db_pwd}}',  host: 'localhost' }
     - { name: 'root',                password: '{{pl_mysql_root_pwd}}',host: 'localhost' }