- name: PLAT MySQL Configure | 生成mysql配置文件
  template: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - { src: 'my.cnf.j2',        dest: '{{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}/etc/my.cnf' }
    - { src: 'mysqld.service.j2',dest: '/usr/lib/systemd/system/mysqld.service' }
    
- name: PLAT MySQL Initialization DB | 初始化mysql数据库
  command: ./mysql_install_db --user={{pl_mysql_user}} --basedir={{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}/mysql --datadir={{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}/data
  args:
    chdir: '{{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}/mysql/scripts'

- name: PLAT MySQL Bin Service | 建立mysql执行程序软连接
  file: src='{{item.src}}' dest='{{item.dest}}' state=link
  with_items:
    - { src: '{{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}/mysql/bin/mysql',                 dest: '/usr/bin/mysql' }
    - { src: '{{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}/mysql/bin/mysqladmin',            dest: '/usr/bin/mysqladmin' }
    - { src: '{{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}/mysql/bin/mysqldump',             dest: '/usr/bin/mysqldump' }
    - { src: '{{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}/mysql/bin/mysqlbinlog',           dest: '/usr/bin/mysqlbinlog' }
    - { src: '{{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}/mysql/support-files/mysql.server',dest: '/etc/init.d/mysqld-server' } 
    
- name: PLAT MySQL Firewall | 为mysql开放防火墙限制
  firewalld: port={{pl_mysql_port}}/tcp permanent=true state=enabled
  
- name: change floder owner | 修改mysql文件用户
  file: path='{{pl_mysql_home}}/{{pl_role_type}}/{{pl_server_type}}' owner='{{pl_mysql_user}}' group='{{pl_mysql_user}}' recurse=yes
  
- name: PLAT MySQL start | 启动mysql
  systemd: name='{{item.name}}' state='{{item.state}}' enabled=yes
  with_items:
    - { name: 'firewalld',state: 'reloaded' }
    - { name: 'mysqld',   state: 'started' }