- name: ZooKeeper JDK Source Package | 解压jdk软件包
  unarchive: 
    src:     '{{item.src}}' 
    dest:    '{{item.dest}}'
    owner:   '{{pl_zookeeper_user}}' 
    group:   '{{pl_zookeeper_user}}'
  with_items:
    - { src: 'jdk-{{pl_jdk_version}}-linux-x64.tar.gz',   dest: '{{pl_zookeeper_home}}/{{pl_role_type}}/{{pl_server_type}}' }

- name: ZooKeeper JDK Floder Owner | 变更jdk目录用户
  file: 
    path: '{{item.path}}' 
    owner: '{{pl_zookeeper_user}}' 
    group: '{{pl_zookeeper_user}}' 
    recurse: yes
  with_items:
    - { path: '{{pl_zookeeper_home}}/{{pl_role_type}}/{{pl_server_type}}/jdk{{pl_jdk_version}}' }