- name: ZooKeeper Group | 创建jzookeeper属组
  group: 
    name: '{{pl_zookeeper_user}}' 
    gid:  '{{pl_zookeeper_id}}'

- name: ZooKeeper User | 创建zookeeper用户
  user: 
    name:  '{{pl_zookeeper_user}}'
    group: '{{pl_zookeeper_user}}'    
    uid:   '{{pl_zookeeper_id}}' 
    shell: /bin/bash

- name: ZooKeeper Floder | 创建zookeeper目录
  file: 
    path:  '{{item}}' 
    mode: 0755 
    state: 'directory'
  with_items:
    - '{{pl_zookeeper_home}}'
    - '{{pl_zookeeper_home}}/{{pl_role_type}}'
    - '{{pl_zookeeper_home}}/{{pl_role_type}}/{{pl_server_type}}'
    - '{{pl_zookeeper_home}}/{{pl_role_type}}/{{pl_server_type}}/zkdata'
    - '{{pl_zookeeper_home}}/{{pl_role_type}}/{{pl_server_type}}/zkdatalog'
    - '{{pl_zookeeper_home}}/{{pl_role_type}}/{{pl_server_type}}/logs'