- name: Rsa_Pub | 部署公钥
  authorized_key: 
    user=root 
    key="{{ lookup('file','/root/.ssh/id_rsa.pub')}}"

- import_tasks: support.yml
  tags:
    - support

- import_tasks: system_config.yml
  tags: 
    - system_config
 
- name: YumRepo | 更新yum软件源
  copy:
    src:  '{{item.src}}'
    dest: '{{item.dest}}'
  with_items:
    - { src: 'centos7_{{pl_yum_repo}}_CentOS-Base.repo',dest: '/etc/yum.repos.d/CentOS-Base.repo' }
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Selinux | 关闭selinux
  selinux:
    state: disabled

- name: Timezone | 修改时区
  timezone:
    name: '{{pl_timezone}}'

- name: Hostname | 修改计算机名
  hostname:
    name: '{{pl_hostname}}'

#- name: Plat Hosts
#  lineinfile:
#    line: '{{hosts_list}}'
#    path: '/etc/hosts'
#    backup: yes
#  tags:
#    - plat_hosts
  
- name: Reboot | 重启服务器
  reboot:
    reboot_timeout: 600
    pre_reboot_delay: 90