- name: Samba Source Package
  unarchive: src=samba-{{pl_samba_version}}.tar.gz dest={{pl_deploy_home}}

- name: Samba Make Configure 
  command: ./configure --prefix={{pl_samba_home}}/samba --systemd-install-services
#  become_user: '{{pl_samba_user}}'
  args:
    chdir: '{{pl_deploy_home}}/samba-{{pl_samba_version}}'

#- name: make install samba
#  make:
#    chdir: '{{pl_deploy_home}}/samba-{{pl_samba_version}}'
#    target: install
#    params:
#      NUM_THREADS: 4
  
- name: Samba Make Install
  shell: make -j 4 && make install
#  become_user: '{{pl_samba_user}}'
  args:
    chdir: '{{pl_deploy_home}}/samba-{{pl_samba_version}}' 