- name: add group for mount
  group: 
    name: '{{pl_samba_mount_group}}' 
    gid:  '{{pl_samba_mount_gid}}'
    state: present

- name: add user for mount
  user: 
    name:  '{{pl_samba_mount_user}}'
    group: '{{pl_samba_mount_group}}'    
    uid:   '{{pl_samba_mount_uid}}' 
    shell: /bin/bash
    state: present

- name: make floder for use 
  file: 
    path:  '{{item.path}}' 
    owner: '{{item.owner}}' 
    group: '{{item.group}}' 
    mode: 0755
    state: '{{item.state}}'
  with_items:
    - { path: '{{pl_samba_mounted_path}}', owner: '{{pl_samba_mount_user}}', group: '{{pl_samba_mount_group}}', state: directory } 
    
#- name: mount samba 
#  shell: mount.cifs //{{pl_samba_mount_server}}/{{pl_samba_workgroup}} {{pl_samba_mounted_path}} -o uid={{pl_samba_mount_uid}},user={{pl_samba_mount_user}},pass={{pl_samba_password}}

#- name: mount samba when restart
#  lineinfile:
#    dest: /etc/fstab
#    line: '{{item}}' 
#    state: present 
#    backup: yes 
#  with_items:
#    -  '//{{pl_samba_mount_server}}/{{pl_samba_workgroup}}    {{pl_samba_mounted_path}}     cifs     defaults,uid=8080,username={{pl_samba_mount_user}},password={{pl_samba_password}}   0 0'

- name: mount samba
  mount:
    src: '//{{pl_samba_mount_server}}/{{pl_samba_workgroup}}'
    path: '{{pl_samba_mounted_path}}'
    state: mounted
    opts: 'uid={{pl_samba_mount_uid}},username={{pl_samba_mount_user}},password={{pl_samba_password}},port={{pl_samba_port}}'
    fstype: cifs
    boot: yes
    
#- name: mount samba when restart
#  lineinfile:
#    dest: /etc/rc.local
#    line: '{{item}}' 
#    state: present 
#    backup: yes 
#  with_items:
#    -  'mount.cifs //{{pl_samba_mount_server}}/{{pl_samba_workgroup}} {{pl_samba_mounted_path}} -o uid={{pl_samba_mount_uid}},user={{pl_samba_mount_user}},pass={{pl_samba_password}}'