- name: Samba Group | 创建samba属组
  group: 
    name: '{{pl_samba_mount_user}}' 
    gid:  '{{pl_samba_mount_id}}'
    state: present

- name: Samba User | 创建samba用户
  user: 
    name:  '{{pl_samba_mount_user}}'
    group: '{{pl_samba_mount_user}}'    
    uid:   '{{pl_samba_mount_id}}' 
    shell: /bin/bash
    state: present

- name: Samba Clear Other Version | 清理其他版本samba
  yum: name=samba state=absent

- name: Samba Floder | 创建samba目录
  file: 
    path:  '{{item.path}}' 
    owner: '{{item.owner}}' 
    group: '{{item.group}}' 
    mode: 0755
    state: '{{item.state}}'
  with_items:
    - { path: '{{pl_deploy_home}}',                                       owner: 'root',                   group: 'root',                    state: directory }
    - { path: '{{pl_samba_home}}',                                        owner: 'root',                   group: 'root',                    state: directory }
    - { path: '{{pl_samba_home}}/{{pl_role_type}}',                       owner: 'root',                   group: 'root',                    state: directory }
    - { path: '{{pl_samba_home}}/{{pl_role_type}}/{{pl_server_type}}',    owner: 'root',                   group: 'root',                    state: directory }
    - { path: '{{pl_samba_home}}/{{pl_role_type}}/{{pl_server_type}}/log',owner: 'root',                   group: 'root',                    state: directory } 
    - { path: '{{pl_samba_mount_path}}',                                  owner: '{{pl_samba_mount_user}}',group: '{{pl_samba_mount_user}}',state: directory } 
