- name: Samba Config | 生成samba配置文件
  template: src='smb.conf.j2' dest='{{pl_samba_home}}/{{pl_role_type}}/{{pl_server_type}}/etc/smb.conf'
    
- name: Samba Mount User | 创建samba挂载用户
  shell: echo -e "{{pl_samba_password}}\n{{pl_samba_password}}" |{{pl_samba_home}}/{{pl_role_type}}/{{pl_server_type}}/bin/smbpasswd -a {{pl_samba_mount_user}} 
